baseURL = "https://carvalho-gustavo.github.io/"
title = "Gustavo Carvalho"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"

[pagination]
pagerSize = 10

[params]
author = "Gustavo Carvalho"
description = "Professional website of Gustavo Carvalho"
keywords = "energy, power markets, strategy, electricity, portfolio"
info = "Market Strategy Director | Power Markets | Energy Economics"
avatarURL = "/images/profile.jpg"
dateFormat = "January 2, 2006"
since = 2026

colorScheme = "dark"
hideColorSchemeToggle = true

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/gpcarvalho/"

[[params.social]]
  name = "CV"
  icon = "fa-solid fa-file-pdf fa-2x"
  weight = 2
  url = "/files/Gustavo_Carvalho_CV_EN.pdf"
  
[[params.social]]
name = "WhatsApp"
icon = "fa-brands fa-whatsapp fa-2x"
weight = 3
url = "https://wa.me/5521975889063"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"
