baseURL = "https://carvalho-gustavo.github.io/"
title = "Gustavo Carvalho"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"

[pagination]
pagerSize = 10

[params]
author = "Gustavo Carvalho"
description = "Website of Gustavo Carvalho"
#keywords = "energy, power markets, strategy, electricity, portfolio"
#info = "Power Systems Economics | Market Design | Strategy & Innovation"
avatarURL = "/images/profile.jpg"
#dateFormat = "January 2, 2006"
#since = 2026

colorScheme = "light"
hideColorSchemeToggle = true

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/gpcarvalho/"

[[params.social]]
  name = "CV"
  icon = "fa-solid fa-file-pdf fa-2x"
  weight = 2
  url = "/files/Gustavo_Carvalho_CV_PT.pdf"

[[params.social]]
name = "Add Contact"
icon = "fa-solid fa-address-card fa-2x"
weight = 3
url = "/files/Gustavo_Carvalho.vcf"
  
[[params.social]]
name = "WhatsApp"
icon = "fa-brands fa-whatsapp fa-2x"
weight = 4
url = "https://wa.me/5521975889063"

# as pastas abaixo ficam dentro da pasta contents, quando quiser que sejam exibidas no site. agora estão arquivadas

#[[menu.main]]
#name = "About"
#weight = 1
#pageRef = "/about/"

#[[menu.main]]
#name = "Articles"
#weight = 2
#pageRef = "/posts/"

#[[menu.main]]
#name = "Insights"
#weight = 2
#pageRef = "/apps/mwavg-energy-calculator/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
